// eslint-disable-next-line no-unused-vars
const a = {
  name: "string",
  religion: "string",
  age: 0,
  mobile: "string",
  gender: 0,
  occupation: "string",
  nationalIdentificationNumber: "string",
  fatherOrHusbandName: "string",
  village: "string",
  union: "string",
  postOffice: "string",
  thana: "string",
  district: "string",
  condition: 0,
  hasGoodPlaceToStay: "string",
  hasSafeToilet: "string",
  hasSafeWaterSource: "string",
  statusList: [1, 2],
  bankAccounts: [
    {
      accountHolderName: "string",
      bankName: "string",
      accountNumber: "string",
      branchName: "string",
    },
  ],
  familyMembers: [
    {
      name: "string",
      age: 0,
      gender: 0,
      educationLevel: "string",
      relationToHof: "string",
      occupation: "string",
      hasDisability: "string",
      isChild: "string",
      isSick: "string",
      isJobless: "string",
      ongoingMedicineOrTreatment: "string",
    },
  ],
  landAndDebtDesc: {
    house: "string",
    land: "string",
    numberOfCows: 0,
    numberOfGoats: 0,
    interestLoanAmount: 0,
    cultivationInstruments: "string",
    numberOfChickenAndDucks: 0,
    existingAssetInCurrency: 0,
    totalDebt: 0,
  },
  debtDescriptions: [
    {
      ngo: 0,
      bank: 0,
      shomobay: 0,
      dadon: 0,
      misc: 0,
      purpose: "string",
    },
  ],
  sourceOfIncome: {
    farming: 0,
    business: 0,
    animals: 0,
    kutirBusiness: 0,
    governmentGrants: 0,
    jobSalary: 0,
    dailyWages: 0,
    totalYearlyIncome: 0,
    misc: 0,
  },
  fieldsOfSpending: {
    food: 0,
    education: 0,
    medicineOrTreatment: 0,
    debtInstallments: 0,
    totalYearlySpending: 0,
    misc: 0,
  },
  healthRelatedInfo: {
    lastingSickness: "string",
    ongoingTreatmentOrMedicine: "string",
    hasPregnancy: "string",
    hasChronicSickness: "string",
    hasCataract: "string",
    hasHearingProblem: "string",
    hasDisability: "string",
    hasHealthEducation: "string",
  },
  criteriaToGrant: {
    insaniat: {
      house: "string",
      food: "string",
      orphan: "string",
      clothes: "string",
    },
    employment: {
      biniyog: "string",
      land: "string",
      kutir: "string",
      cultivatingInstruments: "string",
      cowsOrGoats: "string",
      hensOrDucks: "string",
      business: "string",
      farmingEquipments: "string",
      misc: "string",
    },
    education: {
      childrenEducation: "string",
      educationHelp: "string",
      books: "string",
      instruments: "string",
      childrenClothing: "string",
      food: "string",
      quranEducation: "string",
      misc: "string",
    },
  },
  generalComment: "string",
  programId: 1,
};
