// eslint-disable-next-line no-unused-vars
const a = {
  name: "string",
  religion: "Debitis sint conseq",
  age: 79,
  mobile: "Aliqua Ut aute cons",
  nationalIdentificationNumber: "427",
  gender: "male",
  occupation: "Necessitatibus omnis",
  fatherOrHusbandName: "Cathleen Baldwin",
  village: "Facere nisi deserunt",
  union: "Suscipit voluptatum ",
  postOffice: "Obcaecati provident",
  thana: "Obcaecati sit quia ",
  district: "Debitis rem qui labo",
  condition: 0,
  statusList: [1, 2],
  hasGoodPlaceToStay: "Ut nihil et quia mod",
  hasSafeToilet: "Voluptatem molestia",
  hasSafeWaterSource: "Aperiam sunt eaque ",
  bankAccounts: [
    {
      accountHolderName: "Jonas Frederick",
      bankName: "Hanna Frederick",
      accountNumber: "813",
      branchName: "Lev Poole",
    },
  ],
  familyMembers: [
    {
      name: "Kasper Mcfadden",
      age: 99,
      gender: 0,
      educationLevel: "Magni aut praesentiu",
      relationToHof: "Do illum doloribus ",
      occupation: "Incidunt sunt nesc",
      hasDisability: "Adipisicing culpa m",
      isChild: "Incidunt laboriosam",
      isSick: "Velit aut in sit id",
      isJobless: "Adipisci minus volup",
      ongoingMedicineOrTreatment: "Animi molestiae per",
    },
  ],
  landAndDebtDesc: {
    house: "Eius qui qui ullamco",
    land: "Tempore illo consec",
    numberOfCows: 229,
    numberOfGoats: 771,
    cultivationInstruments: "Consequat Eu autem ",
    numberOfChickenAndDucks: 202,
    existingAssetInCurrency: 52,
    interestLoanAmount: 65,
    totalDebt: 63,
  },
  debtDescriptions: [
    {
      ngo: 77,
      bank: 86,
      shomobay: 47,
      dadon: 41,
      misc: 67,
      purpose: "Molestias voluptate ",
    },
  ],
  sourceOfIncome: {
    farming: 305,
    business: 873,
    animals: 478,
    kutirBusiness: 109,
    governmentGrants: 363,
    jobSalary: 126,
    misc: 528,
    dailyWages: 878,
    totalYearlyIncome: 676,
  },
  fieldsOfSpending: {
    food: 84,
    education: 6,
    medicineOrTreatment: 13,
    debtInstallments: 18,
    misc: 58,
    totalYearlySpending: 2000,
  },
  healthRelatedInfo: {
    lastingSickness: "Sint temporibus sun",
    ongoingTreatmentOrMedicine: "Culpa alias sapiente",
    hasPregnancy: "Temporibus cillum te",
    hasChronicSickness: "Neque doloremque duc",
    hasCataract: "Quia quod dolor cumq",
    hasHearingProblem: "Nulla sit duis exce",
    hasDisability: "Accusamus est quia i",
    hasHealthEducation: "Facilis consequatur",
  },
  criteriaToGrant: {
    insaniat: {
      house: "Odio pariatur Rerum",
      food: "Enim esse aut aut lo",
      orphan: "Ad aut ea sit quia n",
      clothes: "Laboriosam doloremq",
    },
    employment: {
      biniyog: "Voluptate fugiat ips",
      land: "Voluptatem sit et as",
      kutir: "Odio pariatur Itaqu",
      cultivatingInstruments: "Placeat ipsum velit",
      cowsOrGoats: "Non et mollit reicie",
      hensOrDucks: "Perspiciatis conseq",
      business: "Eos non consequat R",
      farmingEquipments: "Ex impedit vitae an",
      misc: "Eaque cum exercitati",
    },
    education: {
      childrenEducation: "Quis itaque sequi qu",
      educationHelp: "Omnis sapiente natus",
      books: "Quisquam fuga Vel e",
      instruments: "Placeat dolor exerc",
      childrenClothing: "Sed illum adipisci ",
      food: "Odio aspernatur volu",
      quranEducation: "Consequuntur asperna",
      misc: "Temporibus anim proi",
    },
  },
  generalComment: "string",
  programId: 1,
};
