#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


echo '🏗️👷 Styling, testing and building before committing'

# Check Prettier standards
npm run format:write ||
(
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run lint ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run typecheck ||
(
    echo 'Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo 'Trying to build now.'

npm run build ||
(
    echo '❌👷🔨❌ Build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
